# vim: syntax=python tabstop=4 expandtab
# coding: utf-8


"""
Variant calling with Freebayes:
https://github.com/ekg/freebayes

Expects a json config file with the following structure, assuming that the
desired reference sequence is some genome
to be found under the given path, and two units A and B have been sequenced with Illumina.

{
    "references": {
        "genome": "path/to/genome.fasta"
    },
    "samples": {
        "A": ["A"],
        "B": ["B"]
    },
    "units": {
        "A":
            ["path/to/A_R1.fastq.gz", "path/to/A_R2.fastq.gz"],
        "B":
            ["path/to/B.fastq.gz"]
    },
    "platform": "Illumina",
    "ploidy": 2,
    "heterozygosity": 0.001,
}

Note the separation between samples and units that allows to have more than
one sequencing run for each sample, or multiple lanes per sample.
"""


__author__ = "Johannes Köster (http://johanneskoester.bitbucket.org)"
__license__ = "MIT"


configfile: "config.json"

include_prefix="https://bitbucket.org/johanneskoester/snakemake-workflows/raw/master"

include:
    include_prefix + "/bio/ngs/rules/mapping/bwa_mem.rules"
include:
    include_prefix + "/bio/ngs/rules/mapping/samfiles.rules"
include:
    include_prefix + "/bio/ngs/rules/variant_calling/freebayes.rules"


rule all:
    input:
        "variant_calling/genome/all.vcf"
